Repository Turbo87/igc-parser, pull requests merged in 2021-02, with the labels that each got.

#203 Add GitHub Actions config
  .github/workflows/ci.yml
  .travis.yml
Labels: internal

#204 Drop support for Node v10 and below
  .github/workflows/ci.yml
  package.json
Labels: breaking

#193 Fix index values for B record extensions
  __snapshots__/test.ts.snap
  index.ts
  test.ts
Labels: bug

#215 Ignore invalid header data sources in lenient mode
  __snapshots__/test.ts.snap
  index.ts
  test.ts
Labels: enhancement

#216 Add `release-it` to simplify the release process
  .release-it.js
  RELEASE.md
  package.json
  yarn.lock
Labels: internal
